### ISSUE TITLE
Same user can get into 2 different rooms

### ISSUE THREAD

**Issue by yixuan-zhou-uzh** [sopra-fs24-group-09/sopra-fs24-group-09-server#146]
![image](https://github.com/sopra-fs24-group-09/sopra-fs24-group-09-server/assets/114996149/64bb31a6-1d7c-4de2-a50c-e738f1c5d325)
By clicking go to last page and clicking another available room quick, one user can get into 2 different rooms.
Entering room needs to verify if the current user is already in a room or not.

**Comment by Zehao-Zhang** [comment]
Fixed already.
1. Add an inRoomId in User entity to track the room that user is in.
2. Set it roomId while create a room or enter a room
3. Set it null while leave a room or game ends
4. Cannot exit room while room is ingame status
5. When enter the room, if the inRoomId is different with the current one, throw an error
