### ISSUE TITLE
[BUG] User cannot reconnect to an ingame room.

### ISSUE THREAD

**Issue by petertheprocess** [sopra-fs24-group-09/sopra-fs24-group-09-server#147]
## Front End Version
sopra-fs24-group-09/sopra-fs24-group-09-client@05b0611ca73fbd5715593937b342293f633e
## Back End Version
38e8624140deeaf3f653036ffe464e74cd340d5a
## Description
If I am playing in a room before and the server crashed. When I re-login, I will see the previous room still exist and I will be redirected to it. When I am redirected to the room, the server log shows
```
Error entering room: No value present
```
and I will be back to lobby. Then redirect to room again, infinite loop formed.

**Comment by petertheprocess** [comment]
If the user reconnect in a room before the 1st round turning, he will loading until the next round. Since no non-empty playsInfo or GameInfo will be sent before round turning.

**Comment by zihanltesla** [comment]
Remove the broadcast, resolved
